name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up latest Oracle JDK 21
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 21

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Install ssh keys
        run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.HOST }} > ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          scp ./build/libs/*SNAPSHOT.jar ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.PATH_TO_DEPLOY }}
          systemctl stop bot.service
          systemctl start bot.service
